spring.application.name=reservas

server.port=8501

eureka.client.service-url.defaultZone=http://localhost:8500/eureka/

# MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/reservasProyecto?createDatabaseIfNotExist=true

spring.datasource.username=root
spring.datasource.password=root1234

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:BD_Config/schema.sql
spring.sql.init.data-locations=classpath:BD_Config/data.sql

# JPA
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
