spring.application.name=comentarios

server.port=8503

eureka.client.service-url.defaultZone=http://localhost:8500/eureka/

# MONGODB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=comentariosProyecto

# GRAPHQL
spring.graphql.graphiql.enabled=true
spring.graphql.path=/comentarios